### ISSUE TITLE
Views/component scopes

### ISSUE THREAD

**Issue by MalikWhitten67** [Postr-Inc/Vader.js#2]
As of version 1.3.1, there's an issue with using state properly within views. It's currently challenging to manage state within components in the same way you would in top-level JavaScript components. The primary problem is that views can access state but struggle to locate the corresponding component in the DOM. This limitation might arise from the fact that Vader runs before the DOM is fully constructed. A potential improvement could involve introducing a mechanism to update components only if they are currently visible or within the DOM.

This enhancement would allow for better integration of state management within Vader views, ensuring that components can efficiently access and manipulate their state while being synchronized with their presence in the DOM.

**Comment by lunoos** [comment]
Hi i would like to work on this issue can u please assign it to me.

**Comment by MalikWhitten67** [comment]
@lunoos  assigned

**Comment by MalikWhitten67** [comment]
This has been resolved in v 1.3.2 - used a timer to resolve when the component touches dom  - then the components scripts are executed.
